### ISSUE TITLE
adjustWorkers is not notified on exit, thus potential resource leak

### ISSUE THREAD

**Issue by oliver258** [devchat-ai/gopool#1]
https://github.com/devchat-ai/gopool/blob/d1a07e8aa342f8df3e82d661198723bcc052dee5/gopool.go#L112C2-L112C2

**Comment by daniel-hutao** [comment]
Thank you for your feedback. I have merged your PR, and I have also added a commit for some optimizations. Please review my changes and see if they are reasonable. Thanks again, you are the first contributor to the current project (excluding myself).

https://github.com/devchat-ai/gopool/commit/2ea0ed3d821afda9732c6e14d7aa900dbabb90f6

**Comment by daniel-hutao** [comment]
I wrote a blog about this issue/pr: [《让 GPT-4 来 review 开源社区贡献者的 PR》](https://www.danielhu.cn/devchat-gpt-in-5min-5-code-review/)
