### ISSUE TITLE
task无法传参

### ISSUE THREAD

**Issue by yp-app** [devchat-ai/gopool#18]
无法将参数传给task func，建议增加传参功能
以map为例
`pool := gopool.NewGoPool(10)
	defer pool.Release()

	for k, v := range myMap {
		pool.AddTask(func() (interface{}, error) {
			log.Println(k, v)
			return nil, nil
		})
	}
	pool.Wait()`
task输出的始终都是最后一条数据

**Comment by daniel-hutao** [comment]
@yp-app 借用 GPT 的一段回复：

如果你的任务需要带参数，你可以通过闭包的方式来实现。你可以在定义任务的时候，将参数包含在闭包中，然后将这个闭包作为任务添加到 GoPool 中。这样在执行任务的时候，就可以访问到这些参数了。

例如，假设你有一个函数 `foo`，它接受一个整数参数 `n`，并返回一个整数和一个错误：

```go
func foo(n int) (int, error) {
    // ...
}
```

你可以通过以下方式将 `foo` 添加到 GoPool 中：

```go
n := 10
pool.AddTask(func() (interface{}, error) {
    return foo(n)
})
```

在这个例子中，`n` 是在定义任务的时候被捕获的，所以在执行任务的时候，`foo` 可以访问到 `n` 的值。

---

因此上面这个需求可以这样解决(手写的伪代码，不一定能直接跑通)：

```go
for k, v := range myMap {
	k1 := k
	v1 := v
	pool.AddTask(func() (interface{}, error) {
		return task(k1, v1)
	})
}

func task(k, v string) (string, error) {
	log.Println(k, v)
	return nil, nil
}
```

**Comment by eric49861** [comment]
@yp-app 不是因为不能传参，是因为你通过的range遍历的map，range循环遍历会有这样的问题，不知道你使用的是go的哪一个版本，目前go的最新版本应该已经尝试解决了该问题，使用闭包传参是一种比较常规的做法

**Comment by yp-app** [comment]
试了一下闭包的方式传参可以，感谢
