### ISSUE TITLE
The goPool is a private type, which cannot be referenced externally for setting types

### ISSUE THREAD

**Issue by hbh112233abc** [devchat-ai/gopool#3]
![image](https://github.com/devchat-ai/gopool/assets/7788164/6ba912d1-aaaf-473a-9e32-5a28c954d3ab)
如下: 我有个服务类,希望加个pool属性
```
type Server struct {
	Setting Setting
	running sync.Map
	pool    gopool.GoPool
}
```
发现gopool内的goPool是私有类型,无法外部引用,能否改为公有类型呢?

**Comment by daniel-hutao** [comment]
收到，马上处理！

I'll do it right now.

**Comment by daniel-hutao** [comment]
https://github.com/devchat-ai/gopool/commit/98d2a096305c27ec87b9abdab319235d03c4f4c4

@hbh112233abc I've add a GoPool interface. Please update your gopool to v0.4.0

**Comment by hbh112233abc** [comment]
厉害哦 我是微信上看到你的文章慕名而来的

**Comment by daniel-hutao** [comment]
@hbh112233abc 哈哈；欢迎试用 GoPool，欢迎提出更多的问题；另外今天还有其他用户提了几个 bug；我会尽快修复然后 release；也请届时你那边记得更新下版本哈。
